### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by mvanio** [adamalbrecht/docx_replace#1]
Hi,

this gem looks extremely useful but gives me permisson denied error when trying to 'doc.commit'. I'm unable to diagnose further.

rails 3.2.1
ruby 1.9.2
rubyzip 0.9.9 (doesn't work with v1.0.0)

**Comment by JMente** [comment]
Hi, @adamalbrecht  i have the same issue, in Linux everything works fine but in Windows environments crash.
