### ISSUE TITLE
Doesnt replace some text

### ISSUE THREAD

**Issue by niquepa** [adamalbrecht/docx_replace#13]
Hi,

im using the gem, and trying to replace 6 strings in the document, but i dont know why, there is only replaced the string on the first paragraph, here is my code:

```
          # Initialize DocxReplace with your template
          doc = DocxReplace::Doc.new("#{Rails.root}/public/CertificadoCapacitacion.docx", "#{Rails.root}/tmp")

          # Replace some variables. $var$ convention is used here, but not required.
          doc.replace("$NOMBRE$", certificado.trainable.user_nombre)
          doc.replace("$CIUDAD$", @training.name)
          doc.replace("$DIAS$", @training.start_date)
          doc.replace("$MES$", (I18n.l @training.end_date, :format => "%B"))
          doc.replace("$HOYDIA$", (I18n.l Time.now, :format => "%d"))
          doc.replace("$HOYMES$", (I18n.l Time.now, :format => "%B"))
          doc.replace("$HOYANIO$", (I18n.l Time.now, :format => "%Y"))

          # Write the document back to a temporary file
          tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp")
          doc.commit(tmp_file.path)
```

And here is the docx content:

![image](https://cloud.githubusercontent.com/assets/2584130/9030171/beacdbe8-3964-11e5-8c44-1483d92608f9.png)

only $NOMBRE$, $CIUDAD$, $DIAS$ and $MES$ are replaced OK, can you help me, thanks.

**Comment by adamalbrecht** [comment]
Sometimes Word adds weird (and invisible) formatting in the middle of a word. You might try just playing with the formatting - maybe retype it and then carefully add the bold parts back in. Or you could open the file with a text editor and see what's really going on (a .docx file is really just a zip file with a bunch of xml files inside).

**Comment by yjchieng** [comment]
It is quite sensitive with formatting. One of the following could potentially caused your problem.
1) Copy and paste the string from another word document.
2) Copy and paste the string from browser.
3) Having multiple format (color, size, etc) in the replacement string.
etc

**Comment by Jbijjer** [comment]
I succeeded by removing the "$" before and after the words and wanted to replace... It worked!  

And you have to make sur that you save under "docx(Document Open XML Strict)" instead of "docx(Word Document)".

Works fine for me now! :+1:

**Comment by Aerotune** [comment]
I created a workaround to replace text even when word splits up works with weird tags. Here's an excerpt from the source code I use.

```
# Replace words that are split by XML tags in Microsoft Word
# e.g. replace the tag {{plejefamilie_cpr}} from:
#  {{</w:t></w:r><w:proofErr w:type=\"spellStart\"/><w:r><w:rPr>
#  <w:rFonts w:cstheme=\"minorHAnsi\"/></w:rPr><w:t>
#  plejefamilie_cp</w:t>r</w:t></w:r><w:r w:rsidRPr=\"00996BA1\">
#  <w:rPr><w:rFonts w:cstheme=\"minorHAnsi\"/></w:rPr><w:t>
#  r</w:t></w:r><w:proofErr w:type=\"spellEnd\"/>
#  <w:r w:rsidRPr=\"00996BA1\"><w:rPr><w:rFonts w:cstheme=\"minorHAnsi\"/>
#  </w:rPr><w:t>}}

XML_TAG = /\<[^\>]+\>/

def word_xml_gsub! word_xml, pattern, replacement
  regexp = //
  tag_pattern = ''
  replacement = replacement.to_s.encode(xml: :text)

  pattern.to_s.each_char.each_with_index do |char, i|
    rc = Regexp.quote(char)
    regexp = /#{regexp}(?<tag#{i}>(#{XML_TAG})*)#{rc}/
    tag_pattern << '\k<tag' + i.to_s + '>'
    tag_pattern << replacement if i == 0
  end

  tag_pattern.force_encoding("ASCII-8BIT")

  word_xml.gsub!(regexp, tag_pattern)
end
```

Then I use it like this:

```
doc = DocxReplace::Doc.new(doc_path, "#{Rails.root}/tmp")
string_to_match = '{{plejefamilie_cpr}}'
replacement = 'yada yada'
word_xml_gsub!(doc.instance_variable_get(:@document_content), string_to_match, replacement)
doc.commit(new_file)
```

It's _really slow_ but it's able to replace text despite words XML tag madness.

**Comment by Aerotune** [comment]
I noticed that if you use smaller tags the tag is less likely to be split up by random XML tags.

**Comment by andresulivam** [comment]
> I created a workaround to replace text even when word splits up works with weird tags. Here's an excerpt from the source code I use.
> 
> ```
> # Replace words that are split by XML tags in Microsoft Word
> # e.g. replace the tag {{plejefamilie_cpr}} from:
> #  {{</w:t></w:r><w:proofErr w:type=\"spellStart\"/><w:r><w:rPr>
> #  <w:rFonts w:cstheme=\"minorHAnsi\"/></w:rPr><w:t>
> #  plejefamilie_cp</w:t>r</w:t></w:r><w:r w:rsidRPr=\"00996BA1\">
> #  <w:rPr><w:rFonts w:cstheme=\"minorHAnsi\"/></w:rPr><w:t>
> #  r</w:t></w:r><w:proofErr w:type=\"spellEnd\"/>
> #  <w:r w:rsidRPr=\"00996BA1\"><w:rPr><w:rFonts w:cstheme=\"minorHAnsi\"/>
> #  </w:rPr><w:t>}}
> 
> XML_TAG = /\<[^\>]+\>/
> 
> def word_xml_gsub! word_xml, pattern, replacement
>   regexp = //
>   tag_pattern = '' # tag_pattern is the resulting replacement with the XML tags intact
>   replacement = replacement.to_s.encode(xml: :text)
>   
>   # Generate tag_pattern and regexp
>   pattern.to_s.each_char.each_with_index do |char, i|
>     rc = Regexp.quote(char)
>     regexp = /#{regexp}(?<tag#{i}>(#{XML_TAG})*)#{rc}/
>     tag_pattern << '\k<tag' + i.to_s + '>'
>     tag_pattern << replacement if i == 0
>   end
> 
>   tag_pattern.force_encoding("ASCII-8BIT")
> 
>   word_xml.gsub!(regexp, tag_pattern)
> end
> ```
> Then I use it like this:
> 
> ```
> doc = DocxReplace::Doc.new(doc_path, "#{Rails.root}/tmp")
> string_to_match = '{{plejefamilie_cpr}}'
> replacement = 'yada yada'
> word_xml_gsub!(doc.instance_variable_get(:@document_content), string_to_match, replacement)
> doc.commit(new_file)
> ```
> It's _really slow_ but it's able to replace text despite Microsoft Word's XML tag madness.

Works for me! Thank you!
